/* EMPLOYEE TABLE CONTAINS ALL EMPLOYEE DETAILS */
CREATE TABLE IF NOT EXISTS EMPLOYEE(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	EMPLOYEEID VARCHAR(30) NOT NULL,
	USERNAME   VARCHAR(30)  NOT NULL,
	PASSWORD  VARCHAR(100) NOT NULL,
	EMAIL   VARCHAR(30)  NOT NULL,
	FIRST_NAME   VARCHAR(30) NOT NULL,
	LAST_NAME   VARCHAR(30) NOT NULL,
	MIDDLE_INITIAL  VARCHAR(30),
	TITLE    VARCHAR(10),
	BIRTHDATE   DATE,
	EMP_HIRE_DATE   DATE,
	GENDER   VARCHAR(6)   NOT NULL,
	SSN   VARCHAR(15) NOT NULL,
	ADDRESSID   INT(10),
	BRANCHID   INT(10),
	ORGANIZATIONID   INT(10),
	NOTES   VARCHAR(255),
	USERSTATUS  VARCHAR(10) NOT NULL,
	DEACTIVATIONDATE  DATE,
	MDALLOWMULTIPLESIGNIN  VARCHAR(10),
	TRANSACTION_ID  INT(10),
    PRIMARY KEY (ID),
	UNIQUE(EMPLOYEEID)
);

/* EMPLOYEE_PROFILE TABLE CONTAINS ALL POSSIBLE ROLES */
CREATE TABLE EMPLOYEE_PROFILE(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    TYPE VARCHAR(30) NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE (TYPE)
);

/* JOIN TABLE FOR MANY-TO-MANY RELATIONSHIP*/ 
CREATE TABLE EMPLOYEE_USER_PROFILE (
    EMPLOYEE_ID BIGINT NOT NULL,
    EMPLOYEE_PROFILE_ID BIGINT NOT NULL,
    PRIMARY KEY (EMPLOYEE_ID , EMPLOYEE_PROFILE_ID ),
    CONSTRAINT FK_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (ID),
    CONSTRAINT FK_EMPLOYEE_PROFILE FOREIGN KEY (EMPLOYEE_PROFILE_ID) REFERENCES EMPLOYEE_PROFILE (ID)
);

/* Populate EMPLOYEE_PROFILE Table */
INSERT INTO EMPLOYEE_PROFILE(type)
VALUES ('USER');
  
INSERT INTO EMPLOYEE_PROFILE(type)
VALUES ('ADMIN');
  
INSERT INTO EMPLOYEE_PROFILE(type)
VALUES ('DBA');

INSERT INTO EMPLOYEE_PROFILE(type)
VALUES ('ADMIN');
  
INSERT INTO EMPLOYEE_PROFILE(type)
VALUES ('EMPLOYEE');

INSERT INTO EMPLOYEE_PROFILE(type)
VALUES ('SUPERADMIN');
  
  
/* POPULATE ONE ADMIN USER WHICH WILL FURTHER CREATE OTHER USERS FOR THE APPLICATION USING GUI password-abc125 */
INSERT INTO EMPLOYEE(EMPLOYEEID, PASSWORD, FIRST_NAME, LAST_NAME, EMAIL,GENDER,SSN,USERNAME,userstatus)
VALUES ('EMP10001','$2a$10$4eqIF5s/ewJwHK1p8lqlFOEm2QIA0S8g6./Lok.pQxqcxaBZYChRm', 'balaji','arumugam','barumugam3@gmail.com','male','232-34-3222','balaji123','ACTIVE');
  
  
/* POPULATE JOIN TABLE */
INSERT INTO EMPLOYEE_USER_PROFILE (EMPLOYEE_ID, EMPLOYEE_PROFILE_ID)
  SELECT EMPLOYEE.ID, PROFILE.ID FROM EMPLOYEE EMPLOYEE, EMPLOYEE_PROFILE PROFILE
  WHERE EMPLOYEE.EMPLOYEEID='EMP10001' AND PROFILE.TYPE='ADMIN';

/* Address Table */
CREATE TABLE ADDRESS(
	ADDRESSID int(10) NOT NULL AUTO_INCREMENT,
	STREET1	 VARCHAR(55),
	STREET2	 VARCHAR(55),
	CITY	 VARCHAR(35),
	STATE	 VARCHAR(20),
	ZIP	     VARCHAR(20),
	PHONE	 VARCHAR(19),
	WORKPHONE  VARCHAR(19),
	EMAIL	  VARCHAR(60),
	FAX	  VARCHAR(20),
    PRIMARY KEY (ADDRESSID));

/* Create persistent_logins Table used to store rememberme related stuff*/
CREATE TABLE persistent_logins (
    username VARCHAR(64) NOT NULL,
    series VARCHAR(64) NOT NULL,
    token VARCHAR(64) NOT NULL,
    last_used TIMESTAMP NOT NULL,
    PRIMARY KEY (series)
);


/* TRANSACTION MANAGEMENT TABLE */	
CREATE TABLE MODELTRANSACTION(
	TRANSACTIONID BIGINT NOT NULL,
	TRANSACTIONNAME VARCHAR(64),
	METHODNAME VARCHAR(64),
	TRANSACTIONTIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	INPUTPARAMETERS VARCHAR(10000),
	CHANGEDESCRIPTION VARCHAR(10000),
	CHANGEDBY VARCHAR(30),
	ENTITYNAME VARCHAR(64),
	ENTITYKEY VARCHAR(64),
	CREATE_USER  varchar(100),
	CREATE_DATE	DATE,
	UPDATE_USER  varchar(100),
	UPDATE_DATE	DATE,
	STATUS varchar(10),
	PRIMARY KEY (TRANSACTIONID)
);	

drop table MODELTRANSACTION;


/* ORGANIZATIONS */
CREATE TABLE ORGANIZATIONS(
OrganizationId BIGINT NOT NULL,
OrganizationName  VARCHAR(64),
OrganizationNumber  VARCHAR(64),
ParentOrganizationId  VARCHAR(64),
PRIMARY KEY (OrganizationId)
);







