/* EMPLOYEE TABLE CONTAINS ALL EMPLOYEE DETAILS */
CREATE TABLE IF NOT EXISTS EMPLOYEE(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	EMPLOYEEID VARCHAR(30) NOT NULL,
	USERNAME   VARCHAR(30)  NOT NULL,
	PASSWORD  VARCHAR(100) NOT NULL,
	EMAIL   VARCHAR(30)  NOT NULL,
	FIRST_NAME   VARCHAR(30) NOT NULL,
	LAST_NAME   VARCHAR(30) NOT NULL,
	MIDDLE_INITIAL  VARCHAR(30),
	TITLE    VARCHAR(10),
	BIRTHDATE   DATE,
	EMP_HIRE_DATE   DATE,
	GENDER   VARCHAR(6)   NOT NULL,
	SSN   VARCHAR(15) NOT NULL,
	ADDRESSID   INT(10),
	BRANCHID   INT(10),
	ORGANIZATIONID   INT(10),
	NOTES   VARCHAR(255),
	USERSTATUS  VARCHAR(10) NOT NULL,
	DEACTIVATIONDATE  DATE,
	MDALLOWMULTIPLESIGNIN  VARCHAR(10),
	TRANSACTION_ID  INT(10),
    PRIMARY KEY (ID),
	UNIQUE(EMPLOYEEID)
);

/* EMPLOYEE_PROFILE TABLE CONTAINS ALL POSSIBLE ROLES */
CREATE TABLE EMPLOYEE_PROFILE(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    TYPE VARCHAR(30) NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE (TYPE)
);

/* JOIN TABLE FOR MANY-TO-MANY RELATIONSHIP*/ 
CREATE TABLE EMPLOYEE_USER_PROFILE (
    EMPLOYEE_ID BIGINT NOT NULL,
    EMPLOYEE_PROFILE_ID BIGINT NOT NULL,
    PRIMARY KEY (EMPLOYEE_ID , EMPLOYEE_PROFILE_ID ),
    CONSTRAINT FK_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (ID),
    CONSTRAINT FK_EMPLOYEE_PROFILE FOREIGN KEY (EMPLOYEE_PROFILE_ID) REFERENCES EMPLOYEE_PROFILE (ID)
);

/* Populate EMPLOYEE_PROFILE Table */
INSERT INTO EMPLOYEE_PROFILE(type)
VALUES ('USER');
  
INSERT INTO EMPLOYEE_PROFILE(type)
VALUES ('ADMIN');
  
INSERT INTO EMPLOYEE_PROFILE(type)
VALUES ('DBA');

INSERT INTO EMPLOYEE_PROFILE(type)
VALUES ('ADMIN');
  
INSERT INTO EMPLOYEE_PROFILE(type)
VALUES ('EMPLOYEE');

INSERT INTO EMPLOYEE_PROFILE(type)
VALUES ('SUPERADMIN');
  
  
/* POPULATE ONE ADMIN USER WHICH WILL FURTHER CREATE OTHER USERS FOR THE APPLICATION USING GUI password-abc125 */
INSERT INTO EMPLOYEE(EMPLOYEEID, PASSWORD, FIRST_NAME, LAST_NAME, EMAIL,GENDER,SSN,USERNAME)
VALUES ('EMP10001','$2A$10$4EQIF5S/EWJWHK1P8LQLFOEM2QIA0S8G6./LOK.PQXQCXABZYCHRM', 'BALAJI','ARUMUGAM','BARUMUGAM3@GMAIL.COM','MALE','232-34-3222','BALAJI123');
  
  
/* POPULATE JOIN TABLE */
INSERT INTO EMPLOYEE_USER_PROFILE (EMPLOYEE_ID, EMPLOYEE_PROFILE_ID)
  SELECT EMPLOYEE.ID, PROFILE.ID FROM EMPLOYEE EMPLOYEE, EMPLOYEE_PROFILE PROFILE
  WHERE EMPLOYEE.EMPLOYEEID='EMP10001' AND PROFILE.TYPE='ADMIN';


CREATE TABLE ADDRESS(
	ADDRESSID int(10) NOT NULL AUTO_INCREMENT,
	STREET1	 VARCHAR(55),
	STREET2	 VARCHAR(55),
	CITY	 VARCHAR(35),
	STATE	 VARCHAR(20),
	ZIP	     VARCHAR(20),
	PHONE	 VARCHAR(19),
	WORKPHONE  VARCHAR(19),
	EMAIL	  VARCHAR(60),
	FAX	  VARCHAR(20),
    PRIMARY KEY (ADDRESSID));


